name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile server
        run: gcc server.c -o server -Wall

      - name: Compile client
        run: gcc client.c -o client -Wall